FROM: python:3.6

COPY ./Audio_Classification_using_LSTM /app
RUN apt update && apt install -y llvm-9 ffmpeg

WORKDIR /app
RUN pip3 install -U pip setuptools wheel
RUN PATH=$PATH:/usr/lib/llvm-9/bin pip3 install -r requirements.txt
